In [2]:
import pandas as pd
import numpy as np
import simplejson as json
import matplotlib.pyplot as plt
import matplotlib as mlt

## Load data

In [3]:
zip_to_county = {}

with open('../data/zip2fips.json', 'r') as f:
    zip_to_county = json.load(f)

In [4]:
df_zips = pd.read_csv('../data/zip_code_database.csv', encoding='latin-1')

In [5]:
df_zips

,zip,type,decommissioned,primary_city,acceptable_cities,unacceptable_cities,state,county,timezone,area_codes,world_region,country,latitude,longitude,irs_estimated_population_2014
0,501,UNIQUE,0,Holtsville,NaN,I R S Service Center,NY,Suffolk County,America/New_York,631,NaN,US,40.81,-73.04,562
1,544,UNIQUE,0,Holtsville,NaN,Irs Service Center,NY,Suffolk County,America/New_York,631,NaN,US,40.81,-73.04,0
2,601,STANDARD,0,Adjuntas,NaN,"Colinas Del Gigante, Jard De Adjuntas, Urb San...",PR,Adjuntas Municipio,America/Puerto_Rico,"787,939",NaN,US,18.16,-66.72,0
3,602,STANDARD,0,Aguada,NaN,"Alts De Aguada, Bo Guaniquilla, Comunidad Las ...",PR,Aguada Municipio,NaN,"787,939",NaN,US,18.38,-67.18,0
4,603,STANDARD,0,Aguadilla,Ramey,"Bda Caban, Bda Esteves, Bo Borinquen, Bo Ceiba...",PR,Aguadilla Municipio,America/Puerto_Rico,787,NaN,US,18.43,-67.15,0
5,604,PO BOX,0,Aguadilla,Ramey,NaN,PR,NaN,NaN,NaN,NaN,US,18.43,-67.15,0
6,605,PO BOX,0,Aguadilla,NaN,NaN,PR,NaN,NaN,NaN,NaN,US,18.43,-67.15,0
7,606,STANDARD,0,Maricao,NaN,Urb San Juan Bautista,PR,Maricao Municipio,America/Puerto_Rico,"787,939",NaN,US,18.18,-66.98,0
8,610,STANDARD,0,Anasco,NaN,"Brisas De Anasco, Est De Valle Verde, Jard De ...",PR,AÃ±asco Municipio,NaN,787,NaN,US,18.28,-67.14,0
9,611,PO BOX,0,Angeles,NaN,NaN,PR,NaN,NaN,NaN,NaN,US,18.28,-66.79,0
10,612,STANDARD,0,Arecibo,NaN,"Alt De Juncos, Alt De San Felipe, Bda Duhamel,...",PR,Arecibo Municipio,America/Puerto_Rico,"787,939",NaN,US,18.45,-66.73,0
11,613,PO BOX,0,Arecibo,NaN,NaN,PR,NaN,NaN,NaN,NaN,US,18.45,-66.73,0
12,614,PO BOX,0,Arecibo,NaN,NaN,PR,NaN,NaN,NaN,NaN,US,18.45,-66.73,0
13,616,STANDARD,0,Bajadero,NaN,Brisas Del Valle,PR,Arecibo Municipio,America/Puerto_Rico,787,NaN,US,18.42,-66.67,0
14,617,STANDARD,0,Barceloneta,NaN,"Bda Catalana, Brisas De Llanadas, Brisas Del M...",PR,Barceloneta Municipio,America/Puerto_Rico,787,NaN,US,18.45,-66.56,0
15,622,STANDARD,0,Boqueron,NaN,Villa Taina,PR,Cabo Rojo Municipio,NaN,787,NaN,US,17.99,-67.15,0
16,623,STANDARD,0,Cabo Rojo,NaN,"Alts De Joyuda, Alts Del Mar, Bo Ballaja, Bo M...",PR,Cabo Rojo Municipio,NaN,787,NaN,US,18.08,-67.14,0
17,624,STANDARD,0,Penuelas,NaN,"Alt De Penuelas Ii, Alts De Penuelas, Brisas D...",PR,PeÃ±uelas Municipio,NaN,787,NaN,US,18.06,-66.72,0
18,627,STANDARD,0,Camuy,NaN,"Alts El Maestro, Sect Pena, Urb Del Carmen, Ur...",PR,Camuy Municipio,NaN,787,NaN,US,18.48,-66.84,0
19,631,PO BOX,0,Castaner,Adjuntas,NaN,PR,Lares Municipio,NaN,NaN,NaN,US,18.19,-66.82,0
20,636,PO BOX,0,Rosario,NaN,NaN,PR,NaN,NaN,NaN,NaN,US,18.15,-67.06,0
21,637,STANDARD,0,Sabana Grande,NaN,"Alts De San Jose, Bda San Isidro, Est Del Rio,...",PR,Sabana Grande Municipio,NaN,787,NaN,US,18.08,-66.96,0
22,638,STANDARD,0,Ciales,NaN,"Qtas De Ciales, Urb Dos Rios, Urb Los Llanos, ...",PR,Ciales Municipio,NaN,787,NaN,US,18.33,-66.47,0
23,641,STANDARD,0,Utuado,NaN,"Alts De Utuado, Bda Nueva, Ext San Martin, Jar...",PR,Utuado Municipio,NaN,787,NaN,US,18.27,-66.70,0
24,646,STANDARD,0,Dorado,NaN,"Bo Arenal, Bo Saldinera, Bosque Dorado, Chalet...",PR,Dorado Municipio,NaN,787,NaN,US,18.47,-66.27,0
25,647,STANDARD,0,Ensenada,NaN,Urb Baco,PR,GuÃ¡nica Municipio,NaN,NaN,NaN,US,17.96,-66.94,0
26,650,STANDARD,0,Florida,NaN,"Alt De Florida, Est De Arroyo, Repto Seoane, U...",PR,Florida Municipio,NaN,"787,939",NaN,US,18.36,-66.56,0
27,652,STANDARD,0,Garrochales,NaN,"Hacienda De Garrochales, Urb Los Jardines",PR,Arecibo Municipio,America/Puerto_Rico,787,NaN,US,18.45,-66.60,0
28,653,STANDARD,0,Guanica,NaN,"Bda Esperanza, Bo La Luna, Urb Bahia, Urb Sagr...",PR,GuÃ¡nica Municipio,NaN,787,NaN,US,17.99,-66.89,0
29,656,STANDARD,0,Guayanilla,NaN,"Bda Guaydia, Bo Los Sitios, Ext Santa Elena 2,...",PR,Guayanilla Municipio,NaN,787,NaN,US,18.02,-66.79,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42583,99811,STANDARD,0,Juneau,NaN,NaN,AK,City and Borough of Juneau,America/Juneau,907,NaN,US,58.47,-134.15,34
42584,99812,UNIQUE,0,Juneau,NaN,State Of Alaska,AK,City and Borough of Juneau,America/Juneau,907,NaN,US,58.28,-134.40,0
42585,99820,PO BOX,0,Angoon,NaN,NaN,AK,Hoonah-Angoon Census Area,NaN,907,NaN,US,57.44,-134.48,373
42586,99821,PO BOX,0,Auke Bay,Juneau,NaN,AK,City and Borough of Juneau,America/Juneau,907,NaN,US,58.30,-134.42,1442
42587,99824,STANDARD,0,Douglas,Juneau,NaN,AK,Juneau City and Borough,America/Juneau,907,NaN,US,58.26,-134.40,1960
42588,99825,PO BOX,0,Elfin Cove,NaN,NaN,AK,Hoonah-Angoon Census Area,America/Juneau,907,NaN,US,58.16,-135.74,70
42589,99826,PO BOX,0,Gustavus,NaN,NaN,AK,Hoonah-Angoon Census Area,America/Juneau,907,NaN,US,58.42,-135.78,483
42590,99827,STANDARD,0,Haines,NaN,NaN,AK,Haines Borough,America/Juneau,907,NaN,US,59.16,-135.86,2170
42591,99829,PO BOX,0,Hoonah,NaN,NaN,AK,Hoonah-Angoon Census Area,America/Juneau,907,NaN,US,58.11,-135.40,808
42592,99830,PO BOX,0,Kake,NaN,NaN,AK,Petersburg Census Area,America/Juneau,907,NaN,US,56.79,-134.19,500
42593,99832,PO BOX,0,Pelican,NaN,NaN,AK,Hoonah-Angoon Census Area,America/Juneau,907,NaN,US,57.95,-136.11,116
42594,99833,PO BOX,0,Petersburg,Kupreanof,NaN,AK,Petersburg Census Area,America/Juneau,907,NaN,US,57.05,-132.62,3432
42595,99835,STANDARD,0,Sitka,NaN,NaN,AK,Sitka City and Borough,America/Juneau,907,NaN,US,56.73,-135.00,7990
42596,99836,PO BOX,0,Port Alexander,"Prt Alexander, Sitka",NaN,AK,Petersburg Census Area,America/Juneau,907,NaN,US,56.24,-134.65,77
42597,99840,PO BOX,0,Skagway,NaN,NaN,AK,Skagway Municipality,America/Juneau,907,NaN,US,59.57,-135.35,1049
42598,99841,PO BOX,0,Tenakee Springs,Tenakee Spgs,NaN,AK,Hoonah-Angoon Census Area,America/Juneau,907,NaN,US,57.79,-135.18,113
42599,99850,PO BOX,0,Juneau,NaN,NaN,AK,City and Borough of Juneau,America/Juneau,907,NaN,US,58.43,-135.38,0
42600,99901,STANDARD,0,Ketchikan,"Edna Bay, Kasaan, Naukati Bay, Saxman",NaN,AK,Ketchikan Gateway Borough,America/Juneau,907,NaN,US,55.61,-131.58,11260
42601,99903,PO BOX,0,Meyers Chuck,Ketchikan,NaN,AK,Wrangell City and Borough,America/Juneau,907,NaN,US,55.68,-132.19,0
42602,99918,PO BOX,0,Coffman Cove,Ketchikan,NaN,AK,Prince of Wales-Hyder Census Area,America/Juneau,907,NaN,US,55.97,-132.74,149
42603,99919,PO BOX,0,Thorne Bay,Ketchikan,NaN,AK,Prince of Wales-Hyder Census Area,America/Juneau,907,NaN,US,55.57,-132.39,517
42604,99921,PO BOX,0,Craig,NaN,NaN,AK,Prince of Wales-Hyder Census Area,America/Juneau,907,NaN,US,55.46,-132.83,1495
42605,99922,PO BOX,0,Hydaburg,NaN,NaN,AK,Prince of Wales-Hyder Census Area,America/Juneau,907,NaN,US,55.20,-132.81,264
42606,99923,PO BOX,0,Hyder,NaN,NaN,AK,Prince of Wales-Hyder Census Area,America/Juneau,907,NaN,US,55.97,-130.04,85
42607,99925,PO BOX,0,Klawock,NaN,NaN,AK,Prince of Wales-Hyder Census Area,America/Juneau,907,NaN,US,55.54,-132.96,733
42608,99926,PO BOX,0,Metlakatla,NaN,NaN,AK,Prince of Wales-Outer Ketchikan Borough,America/Juneau,907,NaN,US,55.14,-131.49,1140
42609,99927,PO BOX,0,Point Baker,NaN,NaN,AK,Prince of Wales-Hyder Census Area,America/Juneau,907,NaN,US,56.30,-133.57,48
42610,99928,PO BOX,0,Ward Cove,NaN,NaN,AK,Ketchikan Gateway Borough,America/Juneau,907,NaN,US,55.45,-131.79,1530
42611,99929,PO BOX,0,Wrangell,NaN,NaN,AK,Wrangell City and Borough,NaN,907,NaN,US,56.41,-131.61,2145
42612,99950,PO BOX,0,Ketchikan,"Edna Bay, Kasaan",NaN,AK,Prince of Wales-Outer Ketchikan Borough,America/Juneau,907,NaN,US,55.34,-131.64,262

In [6]:
df_atus = pd.read_csv('../data/atus_00004.csv', dtype={'COUNTY': str})

In [7]:
df_atus.columns

Index(['CASEID', 'YEAR', 'REGION', 'STATEFIP', 'METRO', 'MSASIZE', 'METAREA',
       'COUNTY', 'HH_SIZE', 'FAMINCOME', 'POVERTY130', 'POVERTY185',
       'POVERTYLEVEL', 'FOODSTAMP', 'WIC', 'HHTENURE', 'HH_CHILD', 'HOUSETYPE',
       'HH_NUMKIDS', 'HH_SIZE_CPS8', 'HH_CHILD_CPS8', 'QFAMINCOME', 'PERNUM',
       'LINENO', 'WT06', 'AGE', 'SEX', 'RACE', 'MARST', 'GENHEALTH', 'HEIGHT',
       'WEIGHT', 'BMI', 'EH_RESP', 'PED', 'SED_EAT', 'FOODSHOP', 'MEALPREP',
       'SODA', 'DIETSODA', 'MILK', 'MEAT', 'STORE', 'STREASON', 'EXERCISE',
       'EXFREQ', 'FASTFD', 'FASTFDFREQ', 'FDTHERM', 'ENOUGHFD', 'ANYSECDRK',
       'ANYSECEAT'],
      dtype='object')

In [8]:
# Drop NaN rows
df_atus.dropna(inplace=True)

In [9]:
df_atus

,CASEID,YEAR,REGION,STATEFIP,METRO,MSASIZE,METAREA,COUNTY,HH_SIZE,FAMINCOME,...,STORE,STREASON,EXERCISE,EXFREQ,FASTFD,FASTFDFREQ,FDTHERM,ENOUGHFD,ANYSECDRK,ANYSECEAT
24774,20140101140007,2014,4,4,1,6,0,4013,3,1,...,2.0,1.0,2.0,99.0,2.0,99.0,2.0,1.0,2.0,1.0
24775,20140101140011,2014,1,42,1,7,6161,42101,2,11,...,1.0,2.0,2.0,99.0,1.0,1.0,2.0,1.0,2.0,1.0
24776,20140101140028,2014,3,48,2,6,0,48000,6,10,...,99.0,99.0,2.0,99.0,2.0,99.0,99.0,1.0,1.0,2.0
24777,20140101140063,2014,3,51,4,0,0,51000,1,1,...,2.0,6.0,2.0,99.0,2.0,99.0,99.0,1.0,1.0,2.0
24778,20140101140168,2014,3,5,4,0,0,5000,2,3,...,1.0,1.0,1.0,5.0,2.0,99.0,2.0,1.0,1.0,2.0
24779,20140101140537,2014,3,24,1,6,8841,24000,2,13,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
24780,20140101140559,2014,3,40,4,0,0,40000,3,11,...,99.0,99.0,1.0,2.0,1.0,3.0,99.0,1.0,1.0,1.0
24781,20140101140610,2014,3,48,1,5,0,48029,3,14,...,2.0,5.0,2.0,99.0,1.0,3.0,2.0,1.0,1.0,1.0
24782,20140101140614,2014,1,42,2,5,0,42003,1,9,...,1.0,3.0,1.0,3.0,1.0,1.0,2.0,1.0,2.0,1.0
24783,20140101140639,2014,4,4,2,6,0,4013,1,15,...,1.0,4.0,1.0,6.0,2.0,99.0,2.0,1.0,2.0,1.0
24784,20140101140665,2014,3,13,2,6,0,13000,2,13,...,3.0,1.0,2.0,99.0,1.0,2.0,2.0,1.0,1.0,2.0
24785,20140101140685,2014,1,44,2,5,0,44000,2,7,...,1.0,1.0,2.0,99.0,1.0,5.0,99.0,1.0,1.0,1.0
24786,20140101140702,2014,3,48,1,5,0,48029,4,4,...,1.0,2.0,2.0,99.0,2.0,99.0,2.0,1.0,1.0,1.0
24787,20140101140725,2014,3,24,2,6,8841,24000,3,16,...,99.0,99.0,2.0,99.0,1.0,5.0,99.0,1.0,1.0,1.0
24788,20140101140759,2014,3,48,1,3,0,48000,2,11,...,99.0,99.0,2.0,99.0,2.0,99.0,99.0,1.0,1.0,1.0
24789,20140101140792,2014,2,27,1,6,5120,27123,2,9,...,99.0,99.0,2.0,99.0,1.0,1.0,99.0,1.0,2.0,1.0
24790,20140101140804,2014,2,26,2,4,3000,26000,4,14,...,99.0,99.0,2.0,99.0,1.0,3.0,99.0,1.0,2.0,2.0
24791,20140101140836,2014,2,55,3,2,460,55000,1,7,...,1.0,2.0,1.0,7.0,2.0,99.0,2.0,1.0,1.0,1.0
24792,20140101140852,2014,1,34,2,7,5601,34003,1,9,...,1.0,2.0,1.0,4.0,2.0,99.0,1.0,1.0,2.0,1.0
24793,20140101140854,2014,4,6,2,7,4481,6037,2,6,...,99.0,99.0,2.0,99.0,1.0,2.0,99.0,1.0,1.0,1.0
24794,20140101140872,2014,3,22,1,5,0,22051,6,14,...,1.0,2.0,1.0,4.0,2.0,99.0,1.0,1.0,1.0,1.0
24795,20140101140875,2014,1,42,2,7,6161,42045,2,13,...,99.0,99.0,2.0,99.0,1.0,1.0,99.0,1.0,1.0,1.0
24796,20140101140876,2014,2,17,3,2,0,17115,2,12,...,2.0,1.0,2.0,99.0,1.0,3.0,2.0,1.0,1.0,2.0
24797,20140101140885,2014,3,24,2,6,8841,24000,1,1,...,1.0,1.0,2.0,99.0,1.0,1.0,2.0,1.0,2.0,2.0
24798,20140101140911,2014,3,13,3,2,0,13000,2,16,...,1.0,3.0,2.0,99.0,1.0,1.0,2.0,1.0,1.0,1.0
24799,20140101140940,2014,3,45,3,2,0,45051,4,14,...,99.0,99.0,2.0,99.0,1.0,2.0,99.0,1.0,1.0,1.0
24800,20140101140958,2014,3,13,2,6,0,13000,4,14,...,1.0,1.0,2.0,99.0,2.0,99.0,99.0,1.0,2.0,1.0
24801,20140101140967,2014,3,37,2,4,3120,37000,1,8,...,2.0,2.0,2.0,99.0,2.0,99.0,2.0,1.0,1.0,1.0
24802,20140101140973,2014,3,13,2,6,0,13135,4,1,...,99.0,99.0,1.0,7.0,2.0,99.0,99.0,1.0,2.0,2.0
24803,20140101140990,2014,3,28,3,0,0,28000,2,11,...,2.0,6.0,1.0,4.0,2.0,99.0,2.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73978,20151211152338,2015,2,29,2,6,0,29189,999,8,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
73979,20151211152344,2015,3,40,5,0,0,40000,999,13,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
73980,20151211152354,2015,2,20,4,0,0,20000,999,11,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
73981,20151211152365,2015,4,6,2,7,4481,6037,999,12,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
73982,20151211152371,2015,3,47,1,5,0,47000,999,6,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
73983,20151211152375,2015,2,27,2,6,0,27000,999,16,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
73984,20151211152387,2015,2,46,3,2,0,46000,999,16,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
73985,20151211152389,2015,1,42,1,7,6161,42101,999,13,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
73986,20151211152391,2015,3,12,1,7,5000,12086,999,7,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
73987,20151211152395,2015,3,48,2,7,1921,48000,999,10,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
73988,20151211152396,2015,3,12,1,3,0,12000,999,15,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
73989,20151211152400,2015,3,47,3,2,1560,47000,999,5,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
73990,20151211152405,2015,3,28,4,0,0,28000,999,3,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
73991,20151211152442,2015,2,18,3,0,0,18000,999,5,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
73992,20151211152445,2015,3,12,2,4,5960,12000,999,7,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
73993,20151211152447,2015,3,37,1,5,0,37119,999,13,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
73994,20151211152448,2015,1,36,2,7,5601,36000,999,2,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
73995,20151211152451,2015,3,12,1,4,0,12009,999,4,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
73996,20151211152455,2015,4,53,2,6,7601,53000,999,16,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
73997,20151211152464,2015,3,12,2,3,0,12113,999,3,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
73998,20151211152490,2015,3,1,2,5,0,1000,999,16,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
73999,20151211152494,2015,4,6,2,6,4481,6000,999,14,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
74000,20151211152497,2015,4,6,2,4,0,6099,999,7,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
74001,20151212150611,2015,2,26,1,6,2161,26163,999,2,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
74002,20151212150614,2015,3,37,1,5,0,37119,999,14,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
74003,20151212150827,2015,4,56,3,0,0,56000,999,11,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
74004,20151212151083,2015,4,6,2,6,0,6073,999,9,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
74005,20151212151177,2015,3,40,2,5,0,40000,999,13,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
74006,20151212151939,2015,4,6,2,7,4481,6037,999,16,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
74007,20151212152469,2015,1,42,2,5,0,42000,999,8,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0

In [10]:
df_atus_orig_size = len(df_atus)

In [18]:
# Count ATU dataset rows where we have no valid county code
# in our zip_to_county map. We can't use those rows.

num_county_zero = 0
num_no_county = 0

avail_fips = zip_to_county.values()

indices_to_drop = []

for idx, row in df_atus.iterrows():
    drop = False
    
    # Skip non-valid county
    if row['COUNTY'][-3:] == '000':
        num_county_zero += 1
        drop = True
    
    elif row['COUNTY'] not in avail_fips:
        num_no_county += 1
        drop = True
    
    if drop:
        indices_to_drop.append(idx)

In [15]:
df_atus.drop(indices_to_drop, inplace=True)

In [21]:
print('Remaining rows: ', len(df_atus))

Remaining rows:  16289